# These values are used for the github action
github:
  mgmt_cluster_name:  lab-mgmt
  runner: ubuntu-22.04
  environment: lab
  account_id: lab-id
  app-clusters:
    - app_cluster_name: lab-app1-cluster
      s3_bucket: lab-cluster-state/lab-app1-cluster
    - app_cluster_name: lab-app2-cluster
      s3_bucket: lab-cluster-state/lab-app2-cluster