on:
  pull_request:

jobs:
  grab-secrets:
    name: grab fake secrets
    runs-on: ubuntu-latest
    outputs:
      test-app-user: ${{ steps.test-app.outputs.test-app-user }}
    steps:
      - name: Add some env vars
        run: |
          app_var1=appVar1
          echo "APP_VAR1=${app_var1}" >> $GITHUB_ENV
          echo "::add-mask::${app_var1}"

      - name: Update env vars
        run: |
          echo "APP_VAR1=" >> $GITHUB_ENV

      - name:
        run: |
          printenv

