on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test version action
    steps:
      # - name: Generate new tag version
      #   id: version
      #   uses: flynshue/version-action@v0.0.1

      - name: test expressions
        env:
          APPLY: ${{ github.event_name == 'push' }}
        id: set
        run: |
          if ${{ env.APPLY }}; then
            echo "apply"
          else
            echo "don't apply"
          fi
