on:
  pull_request:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test version action
    steps:
      - name: Generate new tag version
        id: version
        uses: flynshue/version-action@v0.0.1


      - name: Print version from action
        run: |
          echo "${{ steps.version.outputs.version }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::187592727246:role/gha-ecr-role-madi

      - name: describe repository
        run: |
          aws ecr-public describe-repositories