on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test version action
    steps:
      - name: Generate new tag version
        id: version
        uses: flynshue/version-action@v0.0.1


      - name: test expressions
        id: set
        run: |
          echo "always_apply=${{ github.event_name == 'push' }}"

      - name: call expression
        run: |
          if (${{ steps.set.outputs.always_apply }}); then
            echo "don't apply"
          else
            echo "apply"
          fi