on:
  pull_request:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Test new gha output commands
        id: test
        uses: flynshue/test-workflows/output@test-sha
        with:
          who-to-greet: 'Mona the Octocat'

      - name: Print time from action
        run: |
          echo "${{ steps.id.outputs.time }}"