on: [pull_request]

jobs:
  # hello_world_job:
  #   runs-on: ubuntu-latest
  #   name: A job to say hello
  #   steps:
  #     - name: Make Tag Version
  #       id: version
  #       uses: flynshue/test-workflows/version@test-sha

  #     # Use the output from the `hello` step
  #     - name: Get tag version
  #       run: echo "The tag version ${{ steps.version.outputs.version }}"

  #     - run: echo "GITHUB_HEAD_REF ${{ github.sha }}"

  #     - name: git checkout
  #       uses: actions/checkout@v2

  #     - run: git rev-parse HEAD
  version_job:
    runs-on: ubuntu-latest
    name: read version
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
        with:
          name: ${{ github.sha }}

      # use the output from the `generate-uuid` step
      - name: Get the UUID
        id: versions
        run: |
          tag_version=$(echo "${{ github.sha }}-${{ steps.generate-uuid.outputs.uuid }} | sha1sum")
          echo "::set-output name=version::v$(date +%Y-%d-%m)-${tag_version:0:4}"

      - name: print version
        run: |
          echo "${{ steps.versions.outputs.version }}"

      - name: Test pip template
        env:
          user: fakeUser
          password: fakePassword
        run: |
          cat << EOT >> pip.conf
          [global]
          index-url = https://${{ env.user }}:${{ env.password }}@example.jfrog.io/example/api/pypi/pypi/simple
          EOT

      - name: cat pip.conf
        run: cat pip.conf