on:
  pull_request:
  push:
    branches:
      - main

name: Test Deploy Matrix
jobs:
  install:
    permissions: 
      id-token: write
      contents: read
    strategy:
      matrix:
        include:
          - cluster: sandbox-mgmt
            environment: sandbox
            app_clusters:
              - app_cluster_name: sbx-app1-cluster
                s3_bucket: sandbox-cluster-state/sbx-app1-cluster
              - app_cluster_name: sbx-app2-cluster
                s3_bucket: sandbox-cluster-state/sbx-app2-cluster
          - cluster: lab-mgmt
            environment: lab
            app_clusters:
              - app_cluster_name: lab-app1-cluster
                s3_bucket: lab-cluster-state/lab-app1-cluster
              - app_cluster_name: lab-app2-cluster
                s3_bucket: lab-cluster-state/lab-app2-cluster

    runs-on: ubuntu-latest
    outputs:
      app_clusters: ${{ toJson(matrix.app_clusters) }}
      mgmt_cluster: ${{ steps.app-matrix.outputs.mgmt-cluster }}
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get mmgt cluster
        run: |
          echo "mgmt cluster ${{ matrix.cluster }} in ${{ matrix.environment }}"

      - name: Get app app_clusters
        run: |
          echo "mgmt cluster ${{ matrix.cluster }} app clusters ${{ toJson(matrix.app_clusters) }}"

      # - name: set app cluster matrix
      #   id: app-matrix
      #   run: |
      #     clusters=${{ matrix.app_clusters }}
      #     echo "mgmt-cluster=${{ matrix.cluster }}" >> "$GITHUB_OUTPUT"
      #     {
      #     echo 'app_clusters<<EOF'
      #     echo $clusters
      #     echo EOF
      #     } >> "$GITHUB_OUTPUT"

      # - name: print outputs
      #   run: |
      #     echo ${{ toJson(steps.app-matrix.outputs.app_clusters) }}

  add-cluster:
    runs-on: ubuntu-latest
    needs: [install]
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix: ${{ needs.install.outputs.app_clusters }}
    steps:
      - name: Get s3 bucket info
        run: |
          echo "copy data from ${{ matrix.s3_bucket }}"
